### ISSUE TITLE
HM-TC-IT-WM-W-EU - Temperatur und Feuchtigkeit nicht abfragbar

### ISSUE THREAD

**Issue by alexandergeiler** [hobbyquaker/CUxD-Highcharts#3]
Hallo,

beim neuen Funk-Wandtermostat HM-TC-IT-WM-W-EU ist mit  CUxD-Highcharts keine Auswertung der Datenpunkte Temperatur und Luftfeuchtigkeit möglich.
Die Datenpunkte fehlen einfach.

Gruß
Alexander

**Comment by ptar** [comment]
Hallo,
klappt bei mir mit v.1.4.5

Im Log zu finden unter
```
... NEQxxxxxxx:1.TEMPERATURE 20.4
... NEQxxxxxxx:1.HUMIDITY 56
```` 
Viel Spaß!

**Comment by alexandergeiler** [comment]
Hi,

bei mir mit v.1.4.5 auch.

Gruß
Alexander
